# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SnakeGame

# Build rule for target.
SnakeGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SnakeGame
.PHONY : SnakeGame

# fast build rule for target.
SnakeGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/build
.PHONY : SnakeGame/fast

#=============================================================================
# Target rules for targets named RunTests

# Build rule for target.
RunTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RunTests
.PHONY : RunTests

# fast build rule for target.
RunTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/build
.PHONY : RunTests/fast

src/Food.o: src/Food.cpp.o
.PHONY : src/Food.o

# target to build an object file
src/Food.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Food.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Food.cpp.o
.PHONY : src/Food.cpp.o

src/Food.i: src/Food.cpp.i
.PHONY : src/Food.i

# target to preprocess a source file
src/Food.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Food.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Food.cpp.i
.PHONY : src/Food.cpp.i

src/Food.s: src/Food.cpp.s
.PHONY : src/Food.s

# target to generate assembly for a file
src/Food.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Food.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Food.cpp.s
.PHONY : src/Food.cpp.s

src/GameBoard.o: src/GameBoard.cpp.o
.PHONY : src/GameBoard.o

# target to build an object file
src/GameBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/GameBoard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/GameBoard.cpp.o
.PHONY : src/GameBoard.cpp.o

src/GameBoard.i: src/GameBoard.cpp.i
.PHONY : src/GameBoard.i

# target to preprocess a source file
src/GameBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/GameBoard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/GameBoard.cpp.i
.PHONY : src/GameBoard.cpp.i

src/GameBoard.s: src/GameBoard.cpp.s
.PHONY : src/GameBoard.s

# target to generate assembly for a file
src/GameBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/GameBoard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/GameBoard.cpp.s
.PHONY : src/GameBoard.cpp.s

src/Point.o: src/Point.cpp.o
.PHONY : src/Point.o

# target to build an object file
src/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Point.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Point.cpp.o
.PHONY : src/Point.cpp.o

src/Point.i: src/Point.cpp.i
.PHONY : src/Point.i

# target to preprocess a source file
src/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Point.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Point.cpp.i
.PHONY : src/Point.cpp.i

src/Point.s: src/Point.cpp.s
.PHONY : src/Point.s

# target to generate assembly for a file
src/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Point.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Point.cpp.s
.PHONY : src/Point.cpp.s

src/Snake.o: src/Snake.cpp.o
.PHONY : src/Snake.o

# target to build an object file
src/Snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Snake.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Snake.cpp.o
.PHONY : src/Snake.cpp.o

src/Snake.i: src/Snake.cpp.i
.PHONY : src/Snake.i

# target to preprocess a source file
src/Snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Snake.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Snake.cpp.i
.PHONY : src/Snake.cpp.i

src/Snake.s: src/Snake.cpp.s
.PHONY : src/Snake.s

# target to generate assembly for a file
src/Snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/Snake.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/Snake.cpp.s
.PHONY : src/Snake.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnakeGame.dir/build.make CMakeFiles/SnakeGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/main_test.o: tests/main_test.cpp.o
.PHONY : tests/main_test.o

# target to build an object file
tests/main_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/main_test.cpp.o
.PHONY : tests/main_test.cpp.o

tests/main_test.i: tests/main_test.cpp.i
.PHONY : tests/main_test.i

# target to preprocess a source file
tests/main_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/main_test.cpp.i
.PHONY : tests/main_test.cpp.i

tests/main_test.s: tests/main_test.cpp.s
.PHONY : tests/main_test.s

# target to generate assembly for a file
tests/main_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/main_test.cpp.s
.PHONY : tests/main_test.cpp.s

tests/test_food.o: tests/test_food.cpp.o
.PHONY : tests/test_food.o

# target to build an object file
tests/test_food.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_food.cpp.o
.PHONY : tests/test_food.cpp.o

tests/test_food.i: tests/test_food.cpp.i
.PHONY : tests/test_food.i

# target to preprocess a source file
tests/test_food.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_food.cpp.i
.PHONY : tests/test_food.cpp.i

tests/test_food.s: tests/test_food.cpp.s
.PHONY : tests/test_food.s

# target to generate assembly for a file
tests/test_food.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_food.cpp.s
.PHONY : tests/test_food.cpp.s

tests/test_gameboard.o: tests/test_gameboard.cpp.o
.PHONY : tests/test_gameboard.o

# target to build an object file
tests/test_gameboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_gameboard.cpp.o
.PHONY : tests/test_gameboard.cpp.o

tests/test_gameboard.i: tests/test_gameboard.cpp.i
.PHONY : tests/test_gameboard.i

# target to preprocess a source file
tests/test_gameboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_gameboard.cpp.i
.PHONY : tests/test_gameboard.cpp.i

tests/test_gameboard.s: tests/test_gameboard.cpp.s
.PHONY : tests/test_gameboard.s

# target to generate assembly for a file
tests/test_gameboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_gameboard.cpp.s
.PHONY : tests/test_gameboard.cpp.s

tests/test_snake.o: tests/test_snake.cpp.o
.PHONY : tests/test_snake.o

# target to build an object file
tests/test_snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_snake.cpp.o
.PHONY : tests/test_snake.cpp.o

tests/test_snake.i: tests/test_snake.cpp.i
.PHONY : tests/test_snake.i

# target to preprocess a source file
tests/test_snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_snake.cpp.i
.PHONY : tests/test_snake.cpp.i

tests/test_snake.s: tests/test_snake.cpp.s
.PHONY : tests/test_snake.s

# target to generate assembly for a file
tests/test_snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_snake.cpp.s
.PHONY : tests/test_snake.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... RunTests"
	@echo "... SnakeGame"
	@echo "... src/Food.o"
	@echo "... src/Food.i"
	@echo "... src/Food.s"
	@echo "... src/GameBoard.o"
	@echo "... src/GameBoard.i"
	@echo "... src/GameBoard.s"
	@echo "... src/Point.o"
	@echo "... src/Point.i"
	@echo "... src/Point.s"
	@echo "... src/Snake.o"
	@echo "... src/Snake.i"
	@echo "... src/Snake.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/main_test.o"
	@echo "... tests/main_test.i"
	@echo "... tests/main_test.s"
	@echo "... tests/test_food.o"
	@echo "... tests/test_food.i"
	@echo "... tests/test_food.s"
	@echo "... tests/test_gameboard.o"
	@echo "... tests/test_gameboard.i"
	@echo "... tests/test_gameboard.s"
	@echo "... tests/test_snake.o"
	@echo "... tests/test_snake.i"
	@echo "... tests/test_snake.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

